[package]
name = "init_rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.2"
ring = "0.16.20"
sha2 = "0.9.8"
ferris-says = "0.2"
uuid = { version = "0.8", features = ["v4"] }